import { dummyKeywords } from "@/data/dummyKeywords";
import { dummyTrends } from "@/data/dummyTrends";
import { generateAiText } from "@/lib/ai/server";
import { normalizeArticleUrl } from "@/lib/rss";
import { getSalonPromptContext } from "@/lib/salonProfile";
import type { TrendSource } from "@/config/trendSources";
import type { RssArticle } from "@/lib/rss";
import type { SalonRelevance, TrendCategory } from "@/types/trend";

export type AutoGeneratedTrend = {
  title: string;
  url: string;
  category: TrendCategory;
  memo: string;
  tags: string[];
  registered_at: string;
  salon_relevance: SalonRelevance;
};

const autoTrendCategories: TrendCategory[] = [
  "自社サイト",
  "Instagram",
  "YouTube",
  "Pinterest",
  "ヘアカタログ",
  "髪質改善",
  "白髪ぼかし",
  "ヘアカラー",
  "店販",
  "美容ディーラー",
  "海外トレンド",
  "カウンセリング",
  "SNS運用",
];

function today() {
  return new Date().toISOString().slice(0, 10);
}

function extractJsonArray(text: string) {
  const firstBracket = text.indexOf("[");
  const lastBracket = text.lastIndexOf("]");

  if (firstBracket === -1 || lastBracket === -1 || firstBracket >= lastBracket) {
    return null;
  }

  return text.slice(firstBracket, lastBracket + 1);
}

function toCategory(value: unknown, fallback: TrendCategory): TrendCategory {
  return typeof value === "string" &&
    autoTrendCategories.includes(value as TrendCategory)
    ? (value as TrendCategory)
    : fallback;
}

function toStringArray(value: unknown, fallback: string[]) {
  if (!Array.isArray(value)) {
    return fallback;
  }

  const tags = value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.replace(/^#/, "").trim())
    .filter(Boolean);

  return tags.length > 0 ? Array.from(new Set(tags)).slice(0, 8) : fallback;
}

function inferSalonRelevance(text: string): SalonRelevance {
  const normalized = text.toLowerCase();
  const highKeywords = [
    "髪質改善",
    "縮毛矯正",
    "くせ毛",
    "パサつき",
    "艶髪",
    "白髪",
    "大人女性",
    "ホームケア",
    "松江",
  ];
  const mediumKeywords = [
    "ショート",
    "ボブ",
    "ヘアカラー",
    "カラー",
    "トリートメント",
    "美容室",
    "サロン",
  ];
  const highMatches = highKeywords.filter((keyword) =>
    normalized.includes(keyword.toLowerCase()),
  ).length;
  const mediumMatches = mediumKeywords.filter((keyword) =>
    normalized.includes(keyword.toLowerCase()),
  ).length;

  if (highMatches >= 1) {
    return "高";
  }

  if (mediumMatches >= 1) {
    return "中";
  }

  return "低";
}

function toSalonRelevance(
  value: unknown,
  fallbackText: string,
): SalonRelevance {
  return value === "高" || value === "中" || value === "低"
    ? value
    : inferSalonRelevance(fallbackText);
}

function normalizeGeneratedTrends(value: unknown): AutoGeneratedTrend[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item): AutoGeneratedTrend | null => {
      if (!item || typeof item !== "object") {
        return null;
      }

      const record = item as Record<string, unknown>;
      const title = typeof record.title === "string" ? record.title.trim() : "";
      const url = typeof record.url === "string" ? record.url.trim() : "";
      const category = toCategory(record.category, "髪質改善");
      const memo = typeof record.memo === "string" ? record.memo.trim() : "";
      const tags = toStringArray(record.tags, [category]);

      if (!title || !url || !memo) {
        return null;
      }

      return {
        category,
        memo,
        registered_at:
          typeof record.registered_at === "string" && record.registered_at.trim()
            ? record.registered_at.trim()
            : today(),
        salon_relevance: toSalonRelevance(
          record.salon_relevance,
          [title, memo, ...tags].join(" "),
        ),
        tags,
        title,
        url,
      };
    })
    .filter((trend): trend is AutoGeneratedTrend => trend !== null);
}

function createMockTrends(existingUrls: Set<string>, sources: TrendSource[]): AutoGeneratedTrend[] {
  const manualSources = sources
    .filter((source) => source.enabled && source.type === "manual-url")
    .map((source) => ({
      category: toCategory(source.categoryHint, "自社サイト"),
      memo: `${source.name}をもとに、髪質改善・くせ毛・艶髪提案へつなげやすい登録候補です。`,
      registered_at: today(),
      salon_relevance: inferSalonRelevance(
        `${source.name} ${source.note} ${source.categoryHint}`,
      ),
      tags: ["髪質改善", "くせ毛", "艶髪", "カウンセリング"],
      title: `${source.name} 参考URL`,
      url: source.url,
    }));
  const dummyBased = dummyTrends.slice(0, 3).map((trend) => ({
    category: trend.category,
    memo: trend.memo || trend.summary,
    registered_at: today(),
    salon_relevance: inferSalonRelevance(
      `${trend.title} ${trend.memo || trend.summary} ${trend.tags.join(" ")}`,
    ),
    tags: trend.tags.map((tag) => tag.replace(/^#/, "")).slice(0, 6),
    title: trend.title,
    url: trend.url,
  }));

  return [...manualSources, ...dummyBased]
    .filter((trend) => !existingUrls.has(trend.url))
    .slice(0, 5);
}

export async function generateTrendCandidates({
  articles,
  existingCategories,
  existingKeywords,
  existingUrls,
  sources,
}: {
  articles: RssArticle[];
  existingCategories: string[];
  existingKeywords: string[];
  existingUrls: Set<string>;
  sources: TrendSource[];
}) {
  const normalizedExistingUrls = new Set(
    Array.from(existingUrls).map(normalizeArticleUrl),
  );
  const candidateArticles = articles
    .filter(
      (article) => !normalizedExistingUrls.has(normalizeArticleUrl(article.url)),
    )
    .slice(0, 20);

  if (candidateArticles.length === 0) {
    return {
      providerLabel: "モック生成",
      trends: createMockTrends(existingUrls, sources),
    };
  }

  try {
    const salonContext = getSalonPromptContext();
    const result = await generateAiText({
      maxOutputTokens: 2400,
      systemInstruction:
        [
          "あなたは美容師向けのトレンド収集アシスタントです。SNSスクレイピングは禁止です。入力されたRSS記事情報と登録済みキーワードだけをもとに、サロンワークや投稿ネタに使いやすいトレンド候補を日本語で分類してください。",
          "以下のサロン設定に合う候補を優先し、髪質改善、ストレート、くせ毛改善、パサつき改善、艶髪、白髪ぼかし、ホームケア提案に使えるものを高く評価してください。",
          "ヘア、美容、サロン経営と無関係な記事は出力しないでください。本文の転載はせず、短い要約と元記事URLだけを使ってください。",
          salonContext,
        ].join("\n\n"),
      prompt: [
        "以下の記事候補を美容師向けに分類し、必ずJSON配列だけで返してください。",
        `カテゴリ候補: ${autoTrendCategories.join("、")}`,
        `登録済みカテゴリ: ${existingCategories.join("、") || "未登録"}`,
        `登録済みキーワード: ${
          existingKeywords.join("、") ||
          dummyKeywords.map((keyword) => keyword.name).join("、")
        }`,
        `登録日: ${today()}`,
        "各要素のキー: title, url, category, memo, tags, registered_at, salon_relevance",
        "memoは、投稿・カウンセリング・店販・メニュー提案のどれに使いるかが分かる自然な文章にしてください。",
        "tagsは3〜6個、#なしの文字列配列にしてください。",
        "salon_relevanceはef.mayke`sとの関連度として、高・中・低のどれかにしてください。",
        "髪質改善、縮毛矯正、くせ毛、パサつき、艶髪、白髪、大人女性、ショート、ボブ、ホームケア、松江市の美容室集客に関係する記事は関連度を高くしてください。",
        "記事候補:",
        JSON.stringify(candidateArticles, null, 2),
      ].join("\n"),
    });
    const jsonText = extractJsonArray(result.text);

    if (!jsonText) {
      throw new Error("AI returned non-JSON text.");
    }

    const trends = normalizeGeneratedTrends(JSON.parse(jsonText)).filter(
      (trend) =>
        !normalizedExistingUrls.has(normalizeArticleUrl(trend.url)),
    );

    return {
      providerLabel: result.providerLabel,
      trends: trends.length > 0 ? trends : createMockTrends(existingUrls, sources),
    };
  } catch {
    return {
      providerLabel: "モック生成",
      trends: createMockTrends(existingUrls, sources),
    };
  }
}
