import { dummyKeywords } from "@/data/dummyKeywords";
import { dummyTrends } from "@/data/dummyTrends";
import { generateAiText } from "@/lib/ai/server";
import type { TrendSource } from "@/config/trendSources";
import type { RssArticle } from "@/lib/rss";
import type { TrendCategory } from "@/types/trend";

export type AutoGeneratedTrend = {
  title: string;
  url: string;
  category: TrendCategory;
  memo: string;
  tags: string[];
  registered_at: string;
};

const autoTrendCategories: TrendCategory[] = [
  "自社サイト",
  "Instagram",
  "YouTube",
  "Pinterest",
  "ヘアカタログ",
  "髪質改善",
  "白髪ぼかし",
  "ヘアカラー",
  "店販",
  "美容ディーラー",
  "海外トレンド",
  "カウンセリング",
  "SNS運用",
];

function today() {
  return new Date().toISOString().slice(0, 10);
}

function extractJsonArray(text: string) {
  const firstBracket = text.indexOf("[");
  const lastBracket = text.lastIndexOf("]");

  if (firstBracket === -1 || lastBracket === -1 || firstBracket >= lastBracket) {
    return null;
  }

  return text.slice(firstBracket, lastBracket + 1);
}

function toCategory(value: unknown, fallback: TrendCategory): TrendCategory {
  return typeof value === "string" &&
    autoTrendCategories.includes(value as TrendCategory)
    ? (value as TrendCategory)
    : fallback;
}

function toStringArray(value: unknown, fallback: string[]) {
  if (!Array.isArray(value)) {
    return fallback;
  }

  const tags = value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.replace(/^#/, "").trim())
    .filter(Boolean);

  return tags.length > 0 ? Array.from(new Set(tags)).slice(0, 8) : fallback;
}

function normalizeGeneratedTrends(value: unknown): AutoGeneratedTrend[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item): AutoGeneratedTrend | null => {
      if (!item || typeof item !== "object") {
        return null;
      }

      const record = item as Record<string, unknown>;
      const title = typeof record.title === "string" ? record.title.trim() : "";
      const url = typeof record.url === "string" ? record.url.trim() : "";
      const category = toCategory(record.category, "髪質改善");
      const memo = typeof record.memo === "string" ? record.memo.trim() : "";

      if (!title || !url || !memo) {
        return null;
      }

      return {
        category,
        memo,
        registered_at:
          typeof record.registered_at === "string" && record.registered_at.trim()
            ? record.registered_at.trim()
            : today(),
        tags: toStringArray(record.tags, [category]),
        title,
        url,
      };
    })
    .filter((trend): trend is AutoGeneratedTrend => trend !== null);
}

function createMockTrends(existingUrls: Set<string>, sources: TrendSource[]): AutoGeneratedTrend[] {
  const manualSources = sources
    .filter((source) => source.enabled && source.type === "manual-url")
    .map((source) => ({
      category: toCategory(source.categoryHint, "自社サイト"),
      memo: `${source.name}をもとに、髪質改善・くせ毛・艶髪提案へつなげやすい登録候補です。`,
      registered_at: today(),
      tags: ["髪質改善", "くせ毛", "艶髪", "カウンセリング"],
      title: `${source.name} 参考URL`,
      url: source.url,
    }));
  const dummyBased = dummyTrends.slice(0, 3).map((trend) => ({
    category: trend.category,
    memo: trend.memo || trend.summary,
    registered_at: today(),
    tags: trend.tags.map((tag) => tag.replace(/^#/, "")).slice(0, 6),
    title: trend.title,
    url: trend.url,
  }));

  return [...manualSources, ...dummyBased]
    .filter((trend) => !existingUrls.has(trend.url))
    .slice(0, 5);
}

export async function generateTrendCandidates({
  articles,
  existingCategories,
  existingKeywords,
  existingUrls,
  sources,
}: {
  articles: RssArticle[];
  existingCategories: string[];
  existingKeywords: string[];
  existingUrls: Set<string>;
  sources: TrendSource[];
}) {
  const candidateArticles = articles
    .filter((article) => !existingUrls.has(article.url))
    .slice(0, 12);

  if (candidateArticles.length === 0) {
    return {
      providerLabel: "モック生成",
      trends: createMockTrends(existingUrls, sources),
    };
  }

  try {
    const result = await generateAiText({
      maxOutputTokens: 2400,
      systemInstruction:
        "あなたは美容師向けのトレンド収集アシスタントです。SNSスクレイピングは禁止です。入力されたRSS記事情報と登録済みキーワードだけをもとに、サロンワークや投稿ネタに使いやすいトレンド候補を日本語で分類してください。",
      prompt: [
        "以下の記事候補を美容師向けに分類し、必ずJSON配列だけで返してください。",
        `カテゴリ候補: ${autoTrendCategories.join("、")}`,
        `登録済みカテゴリ: ${existingCategories.join("、") || "未登録"}`,
        `登録済みキーワード: ${
          existingKeywords.join("、") ||
          dummyKeywords.map((keyword) => keyword.name).join("、")
        }`,
        `登録日: ${today()}`,
        "各要素のキー: title, url, category, memo, tags, registered_at",
        "memoは、投稿・カウンセリング・店販・メニュー提案のどれに使えるかが分かる自然な文章にしてください。",
        "tagsは3〜6個、#なしの文字列配列にしてください。",
        "記事候補:",
        JSON.stringify(candidateArticles, null, 2),
      ].join("\n"),
    });
    const jsonText = extractJsonArray(result.text);

    if (!jsonText) {
      throw new Error("AI returned non-JSON text.");
    }

    const trends = normalizeGeneratedTrends(JSON.parse(jsonText)).filter(
      (trend) => !existingUrls.has(trend.url),
    );

    return {
      providerLabel: result.providerLabel,
      trends: trends.length > 0 ? trends : createMockTrends(existingUrls, sources),
    };
  } catch {
    return {
      providerLabel: "モック生成",
      trends: createMockTrends(existingUrls, sources),
    };
  }
}
