"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { StatusMessage } from "@/components/ui/StatusMessage";
import type { Trend, TrendCategory } from "@/types/trend";

type AutoGeneratedTrend = {
  title: string;
  url: string;
  category: TrendCategory;
  memo: string;
  tags: string[];
  registered_at: string;
};

type AutoGenerateResponse = {
  generatedCount: number;
  providerLabel: string;
  savedCount: number;
  savedTrends: AutoGeneratedTrend[];
  trends: AutoGeneratedTrend[];
  warnings: string[];
};

type StatusTone = "neutral" | "info" | "success" | "warning" | "error";

type AutoTrendGeneratorProps = {
  onGenerated: (trends: Trend[]) => void;
};

function toTrend(trend: AutoGeneratedTrend, index: number): Trend {
  return {
    category: trend.category,
    heat: "中",
    id: `auto-${trend.registered_at}-${index}-${trend.url}`,
    keywords: trend.tags.length > 0 ? trend.tags : [trend.category],
    memo: trend.memo,
    publishedAt: trend.registered_at,
    registeredAt: trend.registered_at,
    sourceName: "自動生成",
    summary: trend.memo,
    tags: trend.tags,
    title: trend.title,
    url: trend.url,
  };
}

export function AutoTrendGenerator({ onGenerated }: AutoTrendGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [statusTone, setStatusTone] = useState<StatusTone>("neutral");
  const [message, setMessage] = useState(
    "RSSと登録済み情報から、重複しないトレンド候補を自動生成できます。",
  );
  const [result, setResult] = useState<AutoGenerateResponse | null>(null);

  async function handleGenerate() {
    setIsGenerating(true);
    setStatusTone("info");
    setMessage("RSSを確認し、トレンド候補を生成しています。");

    try {
      const response = await fetch("/api/trends/auto-generate", {
        method: "POST",
      });

      if (!response.ok) {
        throw new Error("Failed to auto generate trends.");
      }

      const data = (await response.json()) as AutoGenerateResponse;
      const displayTrends =
        data.savedTrends.length > 0 ? data.savedTrends : data.trends;

      setResult(data);
      onGenerated(displayTrends.map((trend, index) => toTrend(trend, index)));
      setStatusTone(data.savedCount > 0 ? "success" : "warning");
      setMessage(
        data.savedCount > 0
          ? `${data.providerLabel}で${data.savedCount}件を保存しました。`
          : `${data.providerLabel}で候補を生成しました。Supabase未設定または重複のため保存はありません。`,
      );
    } catch {
      setResult(null);
      setStatusTone("error");
      setMessage(
        "自動生成に失敗しました。RSS URL、Supabase設定、AI設定を確認してください。",
      );
    } finally {
      setIsGenerating(false);
    }
  }

  return (
    <section className="rounded-lg border border-teal-200 bg-white p-4 shadow-sm sm:p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold text-stone-950">
            トレンド自動生成
          </h2>
          <p className="mt-2 text-sm leading-6 text-stone-600">
            登録済みURL、キーワード、RSS記事をもとに、美容師向けの登録候補を作ります。SNSスクレイピングは行いません。
          </p>
        </div>
        <Badge tone="info">RSS/URLベース</Badge>
      </div>

      <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center">
        <button
          className="min-h-11 rounded-md bg-teal-700 px-4 text-sm font-semibold text-white hover:bg-teal-800 disabled:cursor-not-allowed disabled:bg-stone-300"
          disabled={isGenerating}
          onClick={handleGenerate}
          type="button"
        >
          {isGenerating ? "自動生成中" : "自動生成する"}
        </button>
        <p className="text-xs leading-5 text-stone-500">
          RSSが取れないサイトはスキップし、アプリ全体は止めません。
        </p>
      </div>

      <div className="mt-4">
        <StatusMessage isLoading={isGenerating} tone={statusTone}>
          {message}
        </StatusMessage>
      </div>

      {result ? (
        <div className="mt-4 rounded-md bg-stone-50 p-3">
          <div className="flex flex-wrap gap-2">
            <Badge tone="success">候補 {result.generatedCount}件</Badge>
            <Badge tone={result.savedCount > 0 ? "success" : "neutral"}>
              保存 {result.savedCount}件
            </Badge>
            <Badge tone="neutral">{result.providerLabel}</Badge>
          </div>
          {result.warnings.length > 0 ? (
            <ul className="mt-3 grid gap-1 text-xs leading-5 text-stone-600">
              {result.warnings.map((warning) => (
                <li key={warning}>・{warning}</li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
