"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { StatusMessage } from "@/components/ui/StatusMessage";
import type { SalonRelevance, Trend, TrendCategory } from "@/types/trend";

type AutoGeneratedTrend = {
  title: string;
  url: string;
  category: TrendCategory;
  memo: string;
  tags: string[];
  registered_at: string;
  salon_relevance: SalonRelevance;
};

type AutoGenerateResponse = {
  generatedCount: number;
  providerLabel: string;
  savedCount: number;
  savedTrends: AutoGeneratedTrend[];
  trends: AutoGeneratedTrend[];
  warnings: string[];
};

type StatusTone = "neutral" | "info" | "success" | "warning" | "error";

type AutoTrendGeneratorProps = {
  onGenerated: (trends: Trend[]) => void;
};

function toTrend(trend: AutoGeneratedTrend, index: number): Trend {
  return {
    category: trend.category,
    heat: "ä¸­",
    id: `auto-${trend.registered_at}-${index}-${trend.url}`,
    keywords: trend.tags.length > 0 ? trend.tags : [trend.category],
    memo: trend.memo,
    publishedAt: trend.registered_at,
    registeredAt: trend.registered_at,
    salonRelevance: trend.salon_relevance,
    sourceName: "è‡ªå‹•ç”Ÿæˆ",
    summary: trend.memo,
    tags: trend.tags,
    title: trend.title,
    url: trend.url,
  };
}

export function AutoTrendGenerator({ onGenerated }: AutoTrendGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [statusTone, setStatusTone] = useState<StatusTone>("neutral");
  const [message, setMessage] = useState(
    "RSSã¨ç™»éŒ²æ¸ˆã¿æƒ…å ±ã‹ã‚‰ã€é‡è¤‡ã—ãªã„ãƒˆãƒ¬ãƒ³ãƒ‰å€™è£œã‚’è‡ªå‹•ç”Ÿæˆã§ãã¾ã™ã€‚",
  );
  const [result, setResult] = useState<AutoGenerateResponse | null>(null);

  async function getResponseErrorMessage(response: Response) {
    try {
      const data = (await response.json()) as { error?: string };
      return data.error ?? "è‡ªå‹•ç”Ÿæˆã«å¤±æ•—ã—ã¾ã—ãŸã€‚";
    } catch {
      return "è‡ªå‹•ç”Ÿæˆã«å¤±æ•—ã—ã¾ã—ãŸã€‚";
    }
  }

  async function handleGenerate() {
    setIsGenerating(true);
    setStatusTone("info");
    setMessage("RSSã‚’ç¢ºèªã—ã€ãƒˆãƒ¬ãƒ³ãƒ‰å€™è£œã‚’ç”Ÿæˆã—ã¦ã„ã¾ã™ã€‚");

    try {
      const response = await fetch("/api/trends/auto-generate", {
        credentials: "same-origin",
        method: "POST",
      });

      if (!response.ok) {
        throw new Error(await getResponseErrorMessage(response));
      }

      const data = (await response.json()) as AutoGenerateResponse;
      const displayTrends =
        data.savedTrends.length > 0 ? data.savedTrends : data.trends;

      setResult(data);
      onGenerated(displayTrends.map((trend, index) => toTrend(trend, index)));
      setStatusTone(data.savedCount > 0 ? "success" : "warning");
      setMessage(
        data.savedCount > 0
          ? `${data.providerLabel}ã§${data.savedCount}ä»¶ã‚’ä¿å­˜ã—ã¾ã—ãŸã€‚`
          : `${data.providerLabel}ã§å€™è£œã‚’ç”Ÿæˆã—ã¾ã—ãŸã€‚Supabaseæœªè¨­å®šã¾ãŸã¯é‡è¤‡ã®ãf8à y/çykf8àkøà`¸à¢¸ào¸àføà¤øà ˜ˆ
NÂˆHØ]Ú
\œ›ÜŠHÂˆÙ]™\İ[
[
NÂˆÙ]İ]\ÕÛ™J™\œ›ÜˆŠNÂˆÙ]Y\ÜØYÙJˆ\œ›Üˆ[œİ[˜Ù[Ùˆ\œ›Ü‚ˆÈ\œ›Ü‹›Y\ÜØYÙBˆˆº!ê¹båyå'ù¢$8àjùi,y¥eøàeøào¸àeøàgøà ””ÔÈT“8à Tİ\X˜\Ùz*+yk¦¸à PRz*+yk¦¸à¤¹è®º*£xàeøài¸àcøàh8àexàa8à ˆ‹ˆ
NÂˆHš[˜[HÂˆÙ]\ÑÙ[™\˜][™Ê˜[ÙJNÂˆBˆB‚ˆ™]\›ˆ
ˆÙXİ[ÛˆÛ\ÜÓ˜[YOHœ›İ[™Y[È›Ü™\ˆ›Ü™\‹]X[LŒ™Ë]Ú]HMÚYİË\ÛHÛNœMH‚ˆ]ˆÛ\ÜÓ˜[YOH™›^›^]Ü˜\][\Ë\İ\\İYKX™]ÙY[ˆØ\LÈ‚ˆ]‚ˆˆÛ\ÜÓ˜[YOH^[È›Û\Ù[ZX›Û^\İÛ™KNML‚ˆ8àâ8àë8àìøàâz!ê¹båyå'ù¢$ˆÚ‚ˆÛ\ÜÓ˜[YOH›]Lˆ^\ÛHXY[™ËMˆ^\İÛ™KMŒ‚ˆ9ænúc,¹®"8àoÕT“8à xà«xàï8àëøàï8àâxà T”Ôú*&9.¢øà¤¸à ¸àj8àjøà yï£¹k®yn*ùd$xàdxàk¹ænúc,¹`&z(ç8à¤¹/g8à¢¸ào¸àfxà ”Ó”øà®xà«øàë8à©8àå8àìøà¬8àkú(c8àa8ào¸àføà¤øà ‚ˆÜ‚ˆÙ]‚ˆ˜YÙHÛ™OHš[™›È””ÔËÕT“8àæxàï8à®OĞ˜YÙO‚ˆÙ]‚‚ˆ]ˆÛ\ÜÓ˜[YOH›]M›^›^XÛÛØ\LÈÛN™›^\›İÈÛNš][\ËXÙ[\ˆ‚ˆ]Û‚ˆÛ\ÜÓ˜[YOH›Z[‹ZLLH›İ[™Y[Y™Ë]X[MÌM^\ÛH›Û\Ù[ZX›Û^]Ú]Hİ™\˜™Ë]X[N\ØX›Y˜İ\œÛÜ‹[›İX[İÙY\ØX›Y˜™Ë\İÛ™KLÌ‚ˆ\ØX›Y^Ú\ÑÙ[™\˜][™ßBˆÛÛXÚÏ^Ú[™QÙ[™\˜]_Bˆ\OH˜]Ûˆ‚ˆ‚ˆÚ\ÑÙ[™\˜][™ÈÈº!ê¹båyå'ù¢$9.+Hˆˆº!ê¹båyå'ù¢$8àfxà¢ÈŸBˆØ]Û‚ˆÛ\ÜÓ˜[YOH^^ÈXY[™ËMH^\İÛ™KML‚ˆ”Ôøàc9cå¸à£8àj¸àa8à­xà©8àâ8àkøà®xà«xààøàåøàeøà xà¨¸àåøàê¹aj9/døàkù«h¸à xào¸àføà¤øà ‚ˆÜ‚ˆÙ]‚‚ˆ]ˆÛ\ÜÓ˜[YOH›]M‚ˆİ]\ÓY\ÜØYÙH\ÓØY[™Ï^Ú\ÑÙ[™\˜][™ßHÛ™O^Üİ]\ÕÛ™_O‚ˆÛY\ÜØYÙ_BˆÔİ]\ÓY\ÜØYÙO‚ˆÙ]‚‚ˆÜ™\İ[È
ˆ]ˆÛ\ÜÓ˜[YOH›]M›İ[™Y[Y™Ë\İÛ™KMLLÈ‚ˆ]ˆÛ\ÜÓ˜[YOH™›^›^]Ü˜\Ø\Lˆ‚ˆ˜YÙHÛ™OHœİXØÙ\ÜÈ¹`&z(çÜ™\İ[™Ù[™\˜]YÛİ[y.íĞ˜YÙO‚ˆ˜YÙHÛ™O^Ü™\İ[œØ]™YÛİ[ˆÈœİXØÙ\ÜÈˆˆ›™]]˜[ŸO‚ˆ9/çykfÜ™\İ[œØ]™YÛİ[y.í‚ˆĞ˜YÙO‚ˆ˜YÙHÛ™OH›™]]˜[Ü™\İ[œ›İšY\“X™[OĞ˜YÙO‚ˆÙ]‚ˆÜ™\İ[Ø\›š[™ÜË›[™İˆÈ
ˆ[Û\ÜÓ˜[YOH›]LÈÜšYØ\LH^^ÈXY[™ËMH^\İÛ™KMŒ‚ˆÜ™\İ[Ø\›š[™ÜË›X\

Ø\›š[™ÊHOˆ
ˆHÙ^O^İØ\›š[™ßO¸àîŞİØ\›š[™ßOÛO‚ˆ
J_Bˆİ[‚ˆ
Hˆ[BˆÙ]‚ˆ
Hˆ[BˆÜÙXİ[Û‚ˆ
NÂŸB