import { NextResponse } from "next/server";
import { fetchRssArticles } from "@/lib/rss";
import { getSupabaseClient } from "@/lib/supabase/client";
import { fetchTrendSourcesForGeneration } from "@/lib/supabase/trendSources";
import {
  type AutoGeneratedTrend,
  generateTrendCandidates,
} from "@/lib/trendGenerator";

export const runtime = "nodejs";

type TrendLinkRow = {
  url: string;
  category: string;
};

type KeywordRow = {
  name: string;
};

function getErrorMessage(error: unknown) {
  if (!error || typeof error !== "object") {
    return "詳細不明";
  }

  const record = error as Record<string, unknown>;
  const message =
    typeof record.message === "string" ? record.message : "詳細不明";
  const code = typeof record.code === "string" ? ` code: ${record.code}` : "";

  return `${message}${code}`;
}

async function insertGeneratedTrends(trends: AutoGeneratedTrend[]) {
  const supabase = getSupabaseClient();

  if (!supabase || trends.length === 0) {
    return {
      savedCount: 0,
      savedTrends: [] as AutoGeneratedTrend[],
    };
  }

  const rows = trends.map((trend) => ({
    category: trend.category,
    memo: trend.memo,
    registered_at: trend.registered_at,
    tags: trend.tags,
    title: trend.title,
    url: trend.url,
  }));
  const { data, error } = await supabase
    .from("trend_links")
    .insert(rows)
    .select("title,url,category,memo,registered_at,tags");

  if (!error) {
    return {
      savedCount: data?.length ?? 0,
      savedTrends: (data ?? []).map((row) => ({
        category: row.category,
        memo: row.memo,
        registered_at: row.registered_at,
        tags: row.tags ?? [],
        title: row.title,
        url: row.url,
      })) as AutoGeneratedTrend[],
    };
  }

  const retryRows = trends.map((trend) => ({
    category: trend.category,
    memo: trend.memo,
    registered_at: trend.registered_at,
    title: trend.title,
    url: trend.url,
  }));
  const retry = await supabase
    .from("trend_links")
    .insert(retryRows)
    .select("title,url,category,memo,registered_at");

  if (retry.error) {
    throw retry.error;
  }

  return {
    savedCount: retry.data?.length ?? 0,
    savedTrends: (retry.data ?? []).map((row, index) => ({
      category: row.category,
      memo: row.memo,
      registered_at: row.registered_at,
      tags: trends[index]?.tags ?? [],
      title: row.title,
      url: row.url,
    })) as AutoGeneratedTrend[],
  };
}

async function runAutoGenerate() {
  const supabase = getSupabaseClient();
  const warnings: string[] = [];
  let existingUrls = new Set<string>();
  let existingCategories: string[] = [];
  let existingKeywords: string[] = [];

  try {
    if (supabase) {
      const [trendResult, keywordResult] = await Promise.all([
        supabase.from("trend_links").select("url,category"),
        supabase.from("keywords").select("name"),
      ]);

      if (trendResult.error) {
        warnings.push(
          `登録済みトレンドの取得に失敗しました。${getErrorMessage(trendResult.error)}`,
        );
      } else {
        const rows = (trendResult.data ?? []) as TrendLinkRow[];
        existingUrls = new Set(rows.map((row) => row.url).filter(Boolean));
        existingCategories = Array.from(
          new Set(rows.map((row) => row.category).filter(Boolean)),
        );
      }

      if (keywordResult.error) {
        warnings.push(
          `登録済みキーワードの取得に失敗しました。${getErrorMessage(keywordResult.error)}`,
        );
      } else {
        existingKeywords = ((keywordResult.data ?? []) as KeywordRow[])
          .map((row) => row.name)
          .filter(Boolean);
      }
    } else {
      warnings.push("Supabaseが未設定のため、保存せず生成結果だけ表示します。");
    }

    const sources = await fetchTrendSourcesForGeneration();
    const manualArticles = sources
      .filter((source) => source.enabled && source.type === "manual-url")
      .map((source) => ({
        categoryHint: source.categoryHint,
        sourceName: source.name,
        summary: source.note,
        title: source.name,
        url: source.url,
      }));
    const rssResult = await fetchRssArticles(sources);
    warnings.push(...rssResult.errors);

    const generation = await generateTrendCandidates({
      articles: [...rssResult.articles, ...manualArticles],
      existingCategories,
      existingKeywords,
      existingUrls,
      sources,
    });
    const uniqueTrends = generation.trends.filter(
      (trend) => !existingUrls.has(trend.url),
    );
    let saved = {
      savedCount: 0,
      savedTrends: [] as AutoGeneratedTrend[],
    };

    try {
      saved = await insertGeneratedTrends(uniqueTrends);
    } catch (error) {
      warnings.push(
        `生成はできましたが、Supabase保存に失敗しました。${getErrorMessage(error)}`,
      );
    }

    return NextResponse.json({
      generatedCount: uniqueTrends.length,
      providerLabel: generation.providerLabel,
      savedCount: saved.savedCount,
      savedTrends: saved.savedTrends,
      sourceCount: sources.filter((source) => source.enabled).length,
      trends: uniqueTrends,
      warnings,
    });
  } catch {
    return NextResponse.json(
      {
        error:
          "トレンド自動生成に失敗しました。RSS URL、AI設定、Vercel環境変数を確認してください。",
      },
      { status: 500 },
    );
  }
}

function isAuthorizedCronRequest(request: Request) {
  const secret = process.env.CRON_SECRET;

  if (!secret) {
    return false;
  }

  return request.headers.get("authorization") === `Bearer ${secret}`;
}

export async function GET(request: Request) {
  if (!isAuthorizedCronRequest(request)) {
    return NextResponse.json(
      { error: "Unauthorized cron request." },
      { status: 401 },
    );
  }

  return runAutoGenerate();
}

export async function POST() {
  return runAutoGenerate();
}
